newspaper/news/urls.py
from django.urls import path
from .views import PostList, PostDetail, CommentList, PostSearch, PostCreateView, PostUpdateView, PostDeleteView, \
    update_me, PostAuthor, PostTag, PostType, ProfileView, subscribe_to_category, unsubscribe_from_category

urlpatterns = [
    path('', PostList.as_view()),  # т. к. сам по себе это класс, то нам надо представить этот класс в виде view.
    # Для этого вызываем метод as_view
    path('news/<int:pk>', PostDetail.as_view()),
    path('comment/', CommentList.as_view()),
    path('search', PostSearch.as_view()),
    path('create', PostCreateView.as_view(), name='post_create'),
    path('delete/<int:pk>', PostDeleteView.as_view(), name='post_delete'),
    path('edit/<int:pk>', PostUpdateView.as_view(), name='post_edit'),
    path('upgrade/', update_me, name='upgrade'),

    # Urls
    path('author/<int:pk>', PostAuthor.as_view(), name='author_name'),
    path('type/<str:name>', PostType.as_view(), name='post_type'),
    path('tag/<int:pk>', PostTag.as_view(), name='post_tag'),

    path('subscribe/<int:pk>', subscribe_to_category, name='sub_cat'),
    path('unsubscribe/<int:pk>', unsubscribe_from_category, name='unsub_cat'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

newspaper/newspaper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('accounts/', include('allauth.urls'))
]


from newspaper import settings


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newspaper/news/models.py
from django.contrib.auth.models import User, Group
from django.db import models
from datetime import datetime
from django.db.models import Sum
from django.urls import reverse # работа со ссылками
from allauth.account.forms import SignupForm


class Author(models.Model):
    """Авторы статей"""
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    ratingAuthor = models.SmallIntegerField(default=0, verbose_name='Рейтинг')
    avatar = models.ImageField(upload_to='photo/img_avatar', blank=True, null=True, verbose_name='Фото')

    def update_rating(self):
        postRat = self.post_set.all().aggregate(postRating=Sum('ratingPost'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.all().aggregate(commentRating=Sum('ratingComment'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.ratingAuthor = pRat * 3 + cRat
        self.save()

    def __str__(self):
        return f'{self.authorUser.username} {self.authorUser.first_name}'

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        ordering = ['-authorUser']  # Сортировка по имени


class Category(models.Model):
    """категории постов + подписчики на эту категорию"""
    name = models.CharField(max_length=100, unique=True, verbose_name='Категория')
    subscribers = models.ManyToManyField(
        User,
        through='CategorySub',
        blank=True,
        verbose_name='Подписчики')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ['-name']  # Сортировка по имени


class Post(models.Model):
    """Статьи/новости"""
    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья')
    )

    choicePost = models.CharField(
        max_length=2,
        choices=CATEGORY_CHOICES,
        default=NEWS,
        verbose_name='Тип поста')  # поле с выбором — «статья» или «новость»
    headingPost = models.CharField(max_length=128, verbose_name='Заголовок')
    textPost = models.TextField(verbose_name='Содержание')
    ratingPost = models.SmallIntegerField(default=0, verbose_name='Рейтинг')
    timeInCreation = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    photo = models.ImageField(upload_to='photo/%Y/%m/%d/', blank=True, null=True, verbose_name='Фото')
    author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name='Автор')
    postCategory = models.ManyToManyField(Category, through='PostCategory', verbose_name='Категории')

    class Meta:
        verbose_name = "Пост/новость"
        verbose_name_plural = "Посты/новости"

    def preview(self):
        return self.textPost[0:123]+'...'

    def like(self):
        self.ratingPost += 1
        self.save()

    def dislike(self):
        self.ratingPost -= 1
        self.save()

    def __str__(self):
        return f'{self.headingPost.title()}: {self.textPost[:60]}'

    def get_absolute_url(self):
        return f'/news/{self.id}'


class PostCategory(models.Model):
    """категирия постов"""
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Пост/новость')
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')

    def __str__(self):
        return f'{self.postThrough.headingPost[:20]}: {self.categoryThrough.name}'

    class Meta:
        verbose_name = "Категория статьи/новости"
        verbose_name_plural = "Категории статей/новостей"


class CategorySub(models.Model):
    """Подписчик на категорию"""
    categorySub = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True,  verbose_name='Категория')
    subscriberUser = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Подписчик')

    def __str__(self):
        return f'{self.subscriberUser.username} подписан на: {self.categorySub.name}'

    class Meta:
        verbose_name = 'Подписчик'
        verbose_name_plural = 'Подписчики'

    def get_category_sub(self):
        return self.categorySub.name

    def get_subscriber_user(self):
        return self.subscriberUser.name


class Comment(models.Model):
    """комментарии к статьям/новостям + рейтинги этих комментариев"""
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    timeInCreation = models.DateTimeField(auto_now_add=True)  # Автоматическое добавление даты создания комментария
    ratingComment = models.SmallIntegerField(default=0)

    def __str__(self):
        return f'{self.commentUser.username} {self.commentUser.first_name} {self.commentPost.headingPost[:20]}'

    def like(self):
        self.ratingComment += 1
        self.save()

    def dislike(self):
        self.ratingComment -= 1
        self.save()


class CommonSignupForm(SignupForm):
    """форма для добавления в группу common при регистрации через allauth"""

    def save(self, request):
        user = super(CommonSignupForm, self).save(request)
        common_group = Group.objects.get(name='common')
        common_group.user_set.add(user)
        return user

newspaper/news/forms.py
from django.forms import ModelForm, TextInput, Textarea, Select, NumberInput, FileInput
from .models import Post


class PostForm(ModelForm):
# в класс мета, как обычно, надо написать модель, по которой будет строится форма и нужные нам поля.
# Мы уже делали что-то похожее с фильтрами.
    class Meta:
        model = Post
        fields = [
            'choicePost',
            'headingPost',
            'textPost',
            'author',
            'photo',
            'postCategory',
        ]

        # widgets = {
        #     'choicePost': Select(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Тип поста'
        #     }),
        #     'headingPost':TextInput(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Заголовок'
        #     }),
        #     'textPost': Textarea(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Содержание'
        #     }),
        #     'ratingPost': NumberInput(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Содержание'
        #     }),
        #     'author': Select(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Автор'
        #     }),
        #     'photo': FileInput(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Фото'
        #     }),
        # }

newspaper/news/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import ListView, DetailView, CreateView, DeleteView
from django.views.generic.edit import UpdateView
from .filters import PostFilter
from .forms import PostForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
# права доступа если нет авторизации на сайте
from django.shortcuts import redirect
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required
from django.urls import resolve
from django.core.mail import EmailMultiAlternatives  # импортируем класс для создание объекта письма с html

from django.template.loader import render_to_string  # импортируем функцию, которая срендерит наш html в текст
from .models import Author, Category, Post, PostCategory, Comment, CategorySub
from .signals import sending_an_email


class PostList(ListView):
    """главная страница с постаринчным выводом"""
    model = Post
    template_name = 'news.html'
    context_object_name = 'news'
    ordering = ['-timeInCreation']
    paginate_by = 10


class PostDetail(DetailView):
    """отдельный пост"""
    model = Post
    template_name = 'new.html'
    context_object_name = 'new'


class CommentList(ListView):
    model = Comment
    context_object_name = 'comments'
    template_name = 'comments.html'


class PostSearch(ListView):
    """страница с поиском редактирование, добавлением и удалением постов"""
    model = Post
    template_name = 'search.html'
    context_object_name = 'post'
    ordering = ['-timeInCreation']
    paginate_by = 5
    form_class = PostForm  # добавляем форм класс, чтобы получать доступ к форме через метод POST

    def get_filter(self):
        return PostFilter(self.request.GET, queryset=super().get_queryset())

    def get_queryset(self):
        return self.get_filter().qs

    def get_context_data(self, *args, **kwargs):
        context = {
            **super().get_context_data(*args, **kwargs),
            'filter': self.get_filter(),
        }

        context['categories'] = Category.objects.all()
        context['form'] = PostForm()
        context['is_not_authors'] = not self.request.user.groups.filter(name='authors').exists()
        # проверка есть ли пользователь в группе Метод exists() возврашает True если группа authors не найдена
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)  # создаём новую форму, забиваем в неё данные из POST-запроса
        if form.is_valid():  # если пользователь ввёл всё правильно и нигде не ошибся, то сохраняем новый пост
            form.save()
        return super().get(request, *args, **kwargs)


class PostCreateView(PermissionRequiredMixin, CreateView):  # доб. параметр если нужно ограничить права
    """добавление поста + разграничение доступа через PermissionRequiredMixin + permission_required """
    template_name = 'post_create.html'
    form_class = PostForm
    permission_required = ('news.add_post', 'news.add_postCategory',)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = PostForm()
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
        return super().get(request, *args, **kwargs)


class PostUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'post_edit.html'
    form_class = PostForm
    permission_required = ('news.change_post', 'news.change_postCategory',)  # редактирование постов

    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Post.objects.get(pk=id)


class PostDeleteView(PermissionRequiredMixin, DeleteView):
    """дженерик для удаления постов"""
    template_name = 'post_delete.html'
    queryset = Post.objects.all()
    success_url = '/'
    permission_required = ('news.delete_post', 'news.delete_postCategory', )  # удаление постов


class ProfileView(ListView):
    """профиль пользователя со списком его подписок на категории"""
    model = CategorySub
    template_name = 'news/profile.html'
    context_object_name = 'categories'


def page_name(r):
    req = resolve(r.path_info).kwargs['name']
    return req


class PostAuthor(ListView):
    model = Post
    template_name = 'news/subcat/filtered.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        self.id = resolve(self.request.path_info).kwargs['pk']
        queryset = Post.objects.filter(author=Author.objects.get(id=self.id))

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(
            self.request.GET, queryset=self.get_queryset())
        context['name'] = Author.objects.get(authorUsername=User.objects.get(id=self.id))

        return context


class PostType(ListView):
    model = Post
    template_name = 'news/subcat/filtered.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        # self.categoryType = self.get_categoryType_display
        self.name = resolve(self.request.path_info).kwargs['name']
        queryset = Post.objects.filter(categoryType=self.name)
        return queryset


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(
            self.request.GET, queryset=self.get_queryset())
        # context['data'] = page_name(self.request)
        context['name'] = self.name

        return context


class PostTag(ListView):
    """страница с тегами и возможностью подписаться на них"""
    model = Post
    template_name = 'news/subcat/filtered.html'
    context_object_name = 'news'
    paginate_by = 10
    ordering = ['-timeInCreation']

    def get_queryset(self):
        self.id = resolve(self.request.path_info).kwargs['pk']
        queryset = Post.objects.filter(postCategory=Category.objects.get(id=self.id))
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(
            self.request.GET, queryset=self.get_queryset())
        context['name'] = Category.objects.get(id=self.id)

        return context


@login_required
def update_me(request):
    """добавления пользователя в группу авторы с проверкой является ли он автором"""
    user = request.user
    authors_group = Group.objects.get(name='authors')
    if not request.user.groups.filter(name='authors').exists():
        authors_group.user_set.add(user)
    return redirect('/')


@login_required
def subscribe_to_category(request, pk):
    """Подписка пользователя в категорию новостей, проверка есть ли он там
    и если нет добавление с отравкой письма, что он подписан"""
    user = request.user
    category_subscribe = Category.objects.get(id=pk)

    if not category_subscribe.subscribers.filter(id=user.id).exists():
        category_subscribe.subscribers.add(user)
        html = render_to_string('news/subcat/subscribers.html', {'categories': category_subscribe, 'user': user})
        subject = f'Вы подписались на категорию: {category_subscribe}'
        list_of_subscribers = user.email.split()  # преобразуем в список с одним значением
        print(f'list_of_subscribers_______________________{list_of_subscribers}')
        sending_an_email(subject, html, list_of_subscribers)  # отпраляем письмо
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def unsubscribe_from_category(request, pk):
    """Отписка пользователя от категории, с проверкой есть он там или нет"""
    user = request.user
    category_unsubscribe = Category.objects.get(id=pk)

    if category_unsubscribe.subscribers.filter(id=user.id).exists():
        category_unsubscribe.subscribers.remove(user)
    return redirect('/profile/')

newspaper/news/templates/new.html
<!--  наследуемся от шаблона default.html, который мы создавали ещё во времена flatpages -->
{% extends 'News/default.html' %}
{% load custom_filters %}
{% load static %}

<!-- Название у нас будет proudcts -->
{% block title %}
{{ new.headingPost|censor }}
{% endblock title %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
            <article class="entry">
<!-- Пост с картинкой -->
            {% if new.photo %}
              <div class="entry-img">
                <img src="{% if new.photo %}{{ new.photo.url }} {% endif %}" alt="" class="img-fluid">
              </div>
            {% endif %}
              <h2 class="entry-title">
                {{ new.headingPost|censor }}
              </h2>

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="blog-single.html">{{ new.author }}</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="blog-single.html"><time datetime="{{ new.timeInCreation|date:'Y-M-d' }}">{{ new.timeInCreation|date:'d M Y' }}</time></a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="blog-single.html">12 Comments</a></li>
                  </ul>
              </div>

              <div class="entry-content">
                <p>
                  {{ new.textPost|censor }}
                </p>
                <div class="entry-footer">
                    <i class="bi bi-folder"></i>
                    <ul class="cats">
                    <li><a href="blog-single.html">{{ new.get_choicePost_display }}</a></li>
                    {% if new.postCategory.all %}
                    <i class="bi bi-tags"></i>
                    <ul class="tags">
                {% for postCategory in new.postCategory.all %}
                        <li><a href="#">{{ postCategory.name }}</a></li>
                {% endfor %}
                    </ul>
                </div>
                {% endif %}
              </div>

            </article><!-- End blog entry -->

<!--Контейнер автора-->
            <div class="blog-author d-flex align-items-center">
              <img src="{% static 'assets/img/blog/blog-author.jpg' %}" class="rounded-circle float-left" alt="">
              <div>
                <h4>{{ new.author }}</h4>
                <div class="social-links">
                  <a href="https://twitters.com/#"><i class="bi bi-twitter"></i></a>
                  <a href="https://facebook.com/#"><i class="bi bi-facebook"></i></a>
                  <a href="https://instagram.com/#"><i class="biu bi-instagram"></i></a>
                </div>
                <p>
                  Itaque quidem optio quia voluptatibus dolorem dolor. Modi eum sed possimus accusantium. Quas repellat voluptatem officia numquam sint aspernatur voluptas. Esse et accusantium ut unde voluptas.
                </p>
              </div>
            </div><!-- End blog author bio -->

<!--Блок коментариев-->
            <div class="blog-comments">


              <h4 class="comments-count">8 Comments</h4>
    {% for comment in new.comment_set.all %}
                <div id="comment-1" class="comment">
                <div class="d-flex">
                  <div class="comment-img"><img src="{% static 'assets/img/blog/comments-1.jpg' %}" alt=""></div>
                  <div>
                    <h5><a href="">{{ comment.commentUser.username }}</a> &#10072; {{ comment.ratingComment }} <a href="#" class="reply"><i class="bi bi-chevron-compact-up"></i></a>
                    &#10072;<a href="#" class="reply"><i class="bi bi-chevron-compact-down"></i></a></h5>
                    <time datetime="2020-01-01">{{ comment.timeInCreation|date:'d M Y' }}</time>
                    <p>{{ comment.text|censor }}</p>
                  </div>
                </div>
                </div>
                    {% endfor %}
            </div>
                <!-- конец блока коментариев-->

                <div class="reply-form">
                <h4>Leave a Reply</h4>
                <p>Your email address will not be published. Required fields are marked * </p>
                <form action="">
                  <div class="row">
                    <div class="col-md-6 form-group">
                      <input name="name" type="text" class="form-control" placeholder="Your Name*">
                    </div>
                    <div class="col-md-6 form-group">
                      <input name="email" type="text" class="form-control" placeholder="Your Email*">
                    </div>
                  </div>
                  <div class="row">
                    <div class="col form-group">
                      <input name="website" type="text" class="form-control" placeholder="Your Website">
                    </div>
                  </div>
                  <div class="row">
                    <div class="col form-group">
                      <textarea name="comment" class="form-control" placeholder="Your Comment*"></textarea>
                    </div>
                  </div>
                  <button type="submit" class="btn btn-primary">Post Comment</button>

                </form>

              </div>



                <!-- End blog entries list -->

{% endblock content %}

newspaper/news/templates/news.html
<!--  наследуемся от шаблона default.html, который мы создавали ещё во времена flatpages -->
{% extends 'News/default.html' %}

{% load custom_filters %}

<!-- Название у нас будет proudcts -->
{% block title %}
News
{% endblock title %}

<!-- В контенте на странице мы выводим все товары -->
       {% block news_length %}
<h2> Все новости: кол-во {{ news|length }} </h2>
       {% endblock news_length %}

       {% block comment %}
<!--    {% if comments %}-->
        {% for comment in comments %}
{{ comment.name }}
        {% endfor %}
<!--    {% else %}-->
<!--        <h5>Комментариев нет</h5>-->
<!--    {% endif %}-->

       {% endblock comment %}


{% block content %}
    {% if news %}
        {% for new in news %}
            <article class="entry">
<!-- Пост с картинкой -->
            {% if new.photo %}
              <div class="entry-img">
                <img src="{% if new.photo %}{{ new.photo.url }} {% endif %}" alt="" class="img-fluid">
              </div>
            {% endif %}
              <h2 class="entry-title">
                <a href="{{ new.get_absolute_url }}">{{ new.headingPost|censor }}</a>
              </h2>

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="blog-single.html">{{ new.author }}</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="blog-single.html"><time datetime="{{ new.timeInCreation|date:'Y-M-d' }}">{{ new.timeInCreation|date:'d M Y' }}</time></a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="blog-single.html">12 Comments</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-folder"></i> <a href="blog-single.html">{{ new.get_choicePost_display }}</a></li>
                </ul>
              </div>

              <div class="entry-content">
                <p>
                  {{ new.textPost|truncatewords:20|censor }}
                </p>
                <div class="entry-footer">
                    {% if new.postCategory.all %}
                    <i class="bi bi-tags"></i>
                    <ul class="tags">
                {% for postCategory in new.postCategory.all %}
                        <li><a href="{% url 'post_tag' postCategory.id %}">{{ postCategory.name }}</a></li>
                {% endfor %}
                    </ul>
                </div>
                {% endif %}
                    <div class="read-more">
                        <a href="{{ new.get_absolute_url }}">Подробнее</a>
                </div>
              </div>

            </article><!-- End blog entry -->
        {% endfor %}
    {% else %}
        <h1>Новостей нет</h1>
    {% endif %}


<!-- закрываем блок с новостями -->
<!-- Проверяем что поддерживается постраничный вывод -->
{% if is_paginated %}

            <div class="blog-pagination">
              <ul class="justify-content-center">
<!-- Если доступна предыдущая страница, то даём ссылку на неё и самую первую страницу -->
                                    {% if page_obj.has_previous %}
<!--Ставим стрелку в лево-->
                                    <li><a href="?page={{ page_obj.previous_page_number }}">&#9668;</a></li>
                                        {% if not page_obj.number == 2 and not page_obj.number == 3 %}
                                        <li><a href="?page=1">1</a></li>
                                        {% endif %}
                                    {% endif %}


<!-- Показываем только текущую страницу и ближайшие к ней, чтобы список не тянулся и не захламлял страницу -->
                                    {% for num in page_obj.paginator.page_range %}
                                        {% if page_obj.number == num %}
                                    <li class="active"><a href="?page={{ num }}">{{ num }}</a></li>
                                        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                    <li><a href="?page={{ num }}">{{ num }}</a></li>
                                        {% endif %}
                                    {% endfor %}
<!-- Если есть следующая страница, то даём ссылку на неё и на самую последнюю страницу -->
                                    {% if page_obj.has_next %}
<!-- Если разница между следующай странице и послденей меньше 2 то не даём ссылку на последнюю страницу -->
                                        {% if not page_obj.next_page_number == page_obj.paginator.num_pages and not page_obj.next_page_number|add:'1' == page_obj.paginator.num_pages %}
                                        <li><a href="">...</a></li>
                                        <li><a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></li>
                                        {% endif %}
                                    <li><a href="?page={{ page_obj.next_page_number }}">&#9658;</a></li>
                                    {% endif %}
              </ul>
            </div>
{% endif %}

{% endblock content %}

newspaper/news/templates/post_create.html
{% extends 'News/default.html' %}
 
{% block title %} Post list {% endblock title %}
 
{% block content %}
<h3 align="center">Добавить Новость/статью</h3>
<div class="col-md-6 pt-3 px-md-2 px-lg-1">
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Добавить на сайт">
</form>
</div>
{% endblock content %}

newspaper/news/templates/post_delete.html
<!--  наследуемся от шаблона default.html, который мы создавали ещё во времена flatpages -->
{% extends 'News/default.html' %}
{% load custom_filters %}

<!-- Название у нас будет proudcts -->
{% block title %}
{{ new.headingPost|censor }}
{% endblock title %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
<h2>Вы действительно хотите удалить эту - {{ post.get_choicePost_display }}?</h2>
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="подтвердить"></form>
<h1>{{ post.headingPost|censor }}</h1>
<p align="right">автор: {{ post.author }} -- {{ post.timeInCreation|date:'d M Y H:m' }}</p>
<hr>
<p style="text-align: left;">{{ post.textPost|censor }}</p>
{% endblock content %}

newspaper/news/templates/post_edit.html
{% extends 'News/default.html' %}
 
{% block title %} Post list {% endblock title %}

{% block content %}
<h3 align="center">Добавить Новость/статью</h3>
<div class="col-md-6 pt-3 px-md-2 px-lg-1">
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}


    <input type="submit" value="Добавить на сайт">
</form>
</div>
{% endblock content %}